apiVersion: v1
kind: Template
metadata:
  name: package-update-cronjob
  annotations:
    description: "Thoth: Package Update Job"
    openshift.io/display-name: "Thoth: Package Update Job"
    version: 0.4.0
    tags: thoth,ai-stacks,aistacks,package-update
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Package
      Update Job to OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    thoth-station.ninja/template-version: 0.4.0
  labels:
    template: package-update-cronjob
    app: thoth
    component: package-update

parameters:
  - description: Registry the ImageStream to be used
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - displayName: Suspend CronJob run
    description: Suspend CronJob run
    required: true
    name: THOTH_SUSPEND_JOB
    value: "true"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    # TODO adjust ansible role so that we dont need a default here
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: package-update
      annotations:
        thoth-station.ninja/template-version: 0.4.0
      labels:
        app: thoth
        component: package-update
    spec:
      schedule: "0 */12 * * *"
      suspend: ${{THOTH_SUSPEND_JOB}}
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 2
      startingDeadlineSeconds: null
      failedJobsHistoryLimit: 4
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: thoth
                component: package-update
            spec:
              containers:
                - image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/package-update-job:${IMAGE_STREAM_TAG}"
                  name: package-update
                  env:
                    - name: KAFKA_BOOTSTRAP_SERVERS
                      value: "stage-kafka-bootstrap-dh-stage-message-bus.cloud.paas.stage.psi.redhat.com:443"
                    - name: KAFKA_CAFILE
                      value: "/mnt/secrets/kafka_ca.crt"
                    - name: KAFKA_TOPIC_RETENTION_TIME_SECONDS
                      value: 60*60*24
                    - name: RSYSLOG_HOST
                      valueFrom:
                        configMapKeyRef:
                          key: rsyslog-host
                          name: thoth
                    - name: RSYSLOG_PORT
                      valueFrom:
                        configMapKeyRef:
                          key: rsyslog-port
                          name: thoth
                    - name: PROMETHEUS_PUSHGATEWAY_URL
                      valueFrom:
                        configMapKeyRef:
                          name: thoth
                          key: metrics-pushgateway-url
                    - name: SENTRY_DSN
                      valueFrom:
                        secretKeyRef:
                          name: thoth
                          key: sentry-dsn
                    - name: THOTH_DEPLOYMENT_NAME
                      valueFrom:
                        configMapKeyRef:
                          key: storage-bucket-name
                          name: thoth
                    - name: KNOWLEDGE_GRAPH_HOST
                      valueFrom:
                        configMapKeyRef:
                          key: postgresql-host
                          name: thoth
                    - name: KNOWLEDGE_GRAPH_PORT
                      value: "5432"
                    - name: KNOWLEDGE_GRAPH_SSL_DISABLED
                      value: "1"
                    - name: KNOWLEDGE_GRAPH_USER
                      valueFrom:
                        secretKeyRef:
                          name: postgresql
                          key: database-user
                    - name: KNOWLEDGE_GRAPH_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: postgresql
                          key: database-password
                    - name: KNOWLEDGE_GRAPH_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: postgresql
                          key: database-name
                  volumeMounts:
                    - name: secrets
                      mountPath: /mnt/secrets
                      readOnly: true
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "500m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
                  livenessProbe:
                    failureThreshold: 1
                    # Give this job 2 hours to finish
                    initialDelaySeconds: 7200
                    periodSeconds: 10
                    tcpSocket:
                      port: 80
              volumes:
                - name: secrets
                  secret:
                    secretName: "kafka-secret"
                    items:
                      - key: kafka_ca.crt
                        path: kafka_ca.crt
              restartPolicy: OnFailure
